# Generated by Django 4.1.3 on 2022-12-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_kategoriresep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='author',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='kategori_produk',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='KategoriProduk',
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
