# Generated by Django 4.1.3 on 2022-12-06 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_remove_produk_author_remove_produk_kategori_produk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(null=True, upload_to='images_resep/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kategori_resep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.kategoriresep')),
            ],
        ),
        migrations.DeleteModel(
            name='Artikel',
        ),
        migrations.DeleteModel(
            name='KategoriArtikel',
        ),
    ]
