# Generated by Django 4.1.3 on 2022-12-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_resep_url_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resep',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='isi',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='slug',
        ),
        migrations.AddField(
            model_name='resep',
            name='author_datePublished',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='author_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='difficulty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='ingredient',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='key',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='resep',
            name='needItem_itemName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='needItem_thumbItem',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='serving',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='step',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='thumb',
            field=models.ImageField(null=True, upload_to='images_resep/'),
        ),
        migrations.AddField(
            model_name='resep',
            name='times',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resep',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
