# Generated by Django 4.1.3 on 2022-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_resep_gambar_remove_resep_isi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='is_from_api',
            field=models.BooleanField(null=True),
        ),
    ]
