# Generated by Django 4.1.3 on 2022-12-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_resep_is_from_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoriresep',
            name='judul',
        ),
        migrations.AddField(
            model_name='kategoriresep',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kategoriresep',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resep',
            name='is_from_api',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
