# Generated by Django 4.1.3 on 2022-12-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_kategoriresep_judul_kategoriresep_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriresep',
            name='is_from_api',
            field=models.BooleanField(null=True),
        ),
    ]
