# Generated by Django 4.1.3 on 2022-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='difficulty_resep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='serving_resep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='thumb_resep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='times_resep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='title_resep',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
