# Generated by Django 4.1.3 on 2022-12-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_bookmarks_difficulty_resep_bookmarks_serving_resep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriresep',
            name='thumb',
            field=models.ImageField(null=True, upload_to='images_kategori_resep/'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
