# Generated by Django 4.1.3 on 2022-12-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_kategoriresep_thumb_alter_resep_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='difficulty_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='key_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='serving_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='thumb_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='times_resep',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='title_resep',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='needItem_itemName',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='needItem_thumbItem',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='resep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resep'),
        ),
    ]
